apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
