apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-jupyterhub
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0750a3343d62ba057
