apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-ray-cpu
  namespace: ray-cpu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
