apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-ray-cpu
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-016b6dd077d577dc3
